### ISSUE TITLE
Documentation of pages

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#1]
Need Proper Documentation of every page

**Comment by AnubhaSharma2709** [comment]
I can work on this. Please assign

**Comment by Sowham-3098** [comment]
Hey @arpitvermaofficial I think README.md need some updation and I also want to add code_of_conduct.md , Contributing.md, and license.md in your project. And if you want also adding contributor's profile section in README.md

**Comment by arpitvermaofficial** [comment]
> Hey @arpitvermaofficial I think README.md need some updation and I also want to add code_of_conduct.md , Contributing.md, and license.md in your project. And if you want also adding contributor's profile section in README.md

Ok, I will raised new issue for README.md and will assign you when the JWOC phase 1 begins.

**Comment by arpitvermaofficial** [comment]
> Hey @arpitvermaofficial I think README.md need some updation and I also want to add code_of_conduct.md , Contributing.md, and license.md in your project. And if you want also adding contributor's profile section in README.md

**Comment by arpitvermaofficial** [comment]
@Sowham-3098  Sure i will assign you.You just have to comment on new same issue as this is not valid as this is created before 15 feb
