### ISSUE TITLE
Documentation Of Qr Scan and Qr Generate Page

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#11]
+

**Comment by bcsamrudh** [comment]
Hey, I would I to contribute.
What should I do.

**Comment by bcsamrudh** [comment]
Could you please give more information about the issue

**Comment by arpitvermaofficial** [comment]
> Could you please give more information about the issue

You have to include comments in pages so that anyone can understand how the code flow works.

**Comment by bcsamrudh** [comment]
Ok.

**Comment by arpitvermaofficial** [comment]
> Ok.
You have to update me with in next two days about yours progress ,any issue you are facing .so that i will maintain your record and give you point in JWOC

**Comment by tmsagarofficial** [comment]
@arpitvermaofficial I would love to work on this issue under jwoc, 
pls assign it to me 😅

**Comment by arpitvermaofficial** [comment]
Ok i will assign to you

**Comment by tmsagarofficial** [comment]
Thanks for assigning it to me ......will submit a PR by eod

**Comment by Code1705** [comment]
I want to contribute to this issue , would you please elaborate about the requirements means exactly what you want to get added as documentation.

**Comment by arpitvermaofficial** [comment]
You have to include comments in pages so that anyone can understand how the code flow works.

**Comment by Code1705** [comment]
could you  give me an example such that I can understand properly.
