### ISSUE TITLE
Improve UI of User Data page

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#12]

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by arpitvermaofficial** [comment]
> can u assign me this issue

Ok work upon it

**Comment by arpitvermaofficial** [comment]
> can u assign me this issue
You have to update me with in next two days about yours progress ,any issue you are facing .so that i will maintain your record and give you point in JWOC

**Comment by RunTerror** [comment]
please assign me this issue

**Comment by arpitvermaofficial** [comment]
Ok  i assign to you create PR to JWOC branch
