### ISSUE TITLE
Improve UI of Students Data Page

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#13]

**Comment by arpitvermaofficial** [comment]
> can u assign me this issue i m interested to work on this issue
I assign only one issue at a time to the same mentee.

**Comment by Khushal747** [comment]
hey, i would like to work under jwoc ,can u please assign me this issue

**Comment by arpitvermaofficial** [comment]
> hey, i would like to work under jwoc ,can u please assign me this issue

Ok i assign this issue to you

**Comment by Khushal747** [comment]
thankyou

**Comment by Khushal747** [comment]
i need an email and password which has access  to login

**Comment by Khushal747** [comment]
khushal7477@gmail.com here is mail id

**Comment by arpitvermaofficial** [comment]
> [khushal7477@gmail.com](mailto:khushal7477@gmail.com) here is mail id

I sent you mail regarding authentication in app .Connect with me on discord on JWOC channel

**Comment by Khushal747** [comment]
ok thankyou ,please share your discord server link
