### ISSUE TITLE
Improve UI of QR Scan Page

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#14]

**Comment by Khushal747** [comment]
hey, I want to work under this issue

**Comment by arpitvermaofficial** [comment]
> hey, I want to work under this issue
Sure, but we have to assign one issue at a time to one mentee. So when you complete the previous issue, then I will assign this to you.

**Comment by Khushal747** [comment]
now i completed previous issue,please assign me this

**Comment by Khushal747** [comment]
i want to work under JWOC

**Comment by arpitvermaofficial** [comment]
Ok i assign to you

**Comment by Code1705** [comment]
i want to contribute to this issue , kindly assign me under JWOC.

**Comment by arpitvermaofficial** [comment]
Ok i assign to you and create pr to JWOC branch

> i want to contribute to this issue , kindly assign me under JWOC.
