### ISSUE TITLE
Create page which shows the past 7 days records of every student 

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#15]

**Comment by Uttkarsh-raj** [comment]
I would like to work on this issue... can you assign me this issue..

**Comment by arpitvermaofficial** [comment]
Ok Uttkarsh i assign to you create pr to JWOC branch

**Comment by arpitvermaofficial** [comment]
Feature Added in Student_Previous.dart file
