### ISSUE TITLE
update the readme

### ISSUE THREAD

**Issue by Code1705** [arpitvermaofficial/RECB-Outii#20]
with proper documentation

**Comment by arpitvermaofficial** [comment]
Ok i will surely assigned you this issue but first of all tell me some details what you want to change in README.md file

**Comment by arpitvermaofficial** [comment]
> with proper documentation

Ok i will surely assigned you this issue but first of all tell me some details what you want to change in README.md file

**Comment by Code1705** [comment]
like a little bit more info about the project and elements to make it attractive, project maintainer rights are with whom basically these points.

**Comment by arpitvermaofficial** [comment]
I think this is not a required issue for now. So I close this issue. If you have any further ideas, then feel free to raise your issue.

**Comment by Code1705** [comment]
okk sure !.
