### ISSUE TITLE
Improve Splash Screen

### ISSUE THREAD

**Issue by arpitvermaofficial** [arpitvermaofficial/RECB-Outii#8]

**Comment by AnubhaSharma2709** [comment]
I can work on this. Please assign

**Comment by arpitvermaofficial** [comment]
Ok, I will assign you when the JWOC phase 1 begins.

**Comment by arpitvermaofficial** [comment]
> I can work on this. Please assign

Ok, I will assign you when the JWOC phase 1 begins.

**Comment by arpitvermaofficial** [comment]
> I can work on this. Please assign

Sure i will assign you.You just have to comment on new same issue as this is not valid as this is created before 15 feb
